sudo: false
language: python
python:
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install .
  - pip install codecov

script:
  - nosetests
  - coverage run

after_success:
  - codecov --token=7f074403-e334-4996-8f09-ebf77c4e593d