#base config
---
  app: "aness"
  api_version: "v1"
  db:
    sa:
      #    SqlAlchemy - The sqlite :memory: identifier is the default if no filepath is present. Specify sqlite:// and nothing else:
      connection: sqlite://
    pw:
       #   Peewee - use :memory:
      connection: ":memory:"
  mongodb:
    connection: ""
  gunicorn:
    bind: 127.0.0.1:8001
#    bind: "unix:/tmp/aness.sock"
#    user: "www-data"
#    group: "www-data"
    workers: 1
    threads: 4
    timeout: 30
    accesslog: "-"
  wsgiref:
    host: 127.0.0.1
    port: 8001
  security:
    token_prefix: "JWT"
    token_expiry: 3600
    tokens_leeway: 0
    tokens_authorize_endpoint: "/auth"
    tokens_enable_refresh: true
    tokens_refresh_endpoint: "auth/refresh"
    secret: "b042cd6b222c1de10bc3432c6bdad55194d0467ee13a2150d7d9e28d9dfe894d"

#oauth config
  social_config:
    base_url: https://aness.retla.net
    sites_list:
      -
        - baidu
        - socialoauth.sites.baidu.Baidu
        - Baidu
        - redirect_uri: oauths/baidu
          client_id: YOUR_ID
          client_secret: YOUR SECRET
          scope:
            - baidu_common
      -
        - github
        - socialoauth.sites.github.Github
        - Github
        - redirect_uri: oauths/github
          client_id: 4f131f2e1304ec60d7c1
          client_secret: 0de4ac8b7319c75d10a3c40226e2b3a0caecaccd
          scope:
            - user
      -
        - decoy
        - socialoauth.sites.decoy.Decoy
        - Decoy
        - redirect_uri: oauths/decoy
          client_id: abc000000000000
          client_secret: abc0000000000000000000000
          scope:
            - user
      -
        - mailru
        - socialoauth.sites.mailru.MailRu
        - Mail.RU
        - redirect_uri: oauths/mailru
          client_id: adqwefwqerf_fake
          client_secret: cbi23gf87h2p3hf92hf39uoh29fhc9oq23h_fake
          scope:
            - user